// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/bridge/bridge.proto

package bridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PacketType 数据包类型
type PacketType int32

const (
	PacketType_UNKNOWN      PacketType = 0
	PacketType_STREAM_OPEN  PacketType = 1 // 打开逻辑流
	PacketType_STREAM_DATA  PacketType = 2 // 数据传输
	PacketType_STREAM_CLOSE PacketType = 3 // 关闭逻辑流
	PacketType_STREAM_ACK   PacketType = 4 // 确认消息
	PacketType_STREAM_ERROR PacketType = 5 // 错误消息
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "UNKNOWN",
		1: "STREAM_OPEN",
		2: "STREAM_DATA",
		3: "STREAM_CLOSE",
		4: "STREAM_ACK",
		5: "STREAM_ERROR",
	}
	PacketType_value = map[string]int32{
		"UNKNOWN":      0,
		"STREAM_OPEN":  1,
		"STREAM_DATA":  2,
		"STREAM_CLOSE": 3,
		"STREAM_ACK":   4,
		"STREAM_ERROR": 5,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_bridge_bridge_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_api_proto_bridge_bridge_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{0}
}

// PacketMetadata 数据包元数据（强类型定义）
type PacketMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId   string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`        // 源节点ID
	TargetNodeId   string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`        // 目标节点ID
	SourceClientId int64                  `protobuf:"varint,3,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"` // 源客户端ID
	TargetClientId int64                  `protobuf:"varint,4,opt,name=target_client_id,json=targetClientId,proto3" json:"target_client_id,omitempty"` // 目标客户端ID
	RequestId      string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                   // 请求ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PacketMetadata) Reset() {
	*x = PacketMetadata{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketMetadata) ProtoMessage() {}

func (x *PacketMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketMetadata.ProtoReflect.Descriptor instead.
func (*PacketMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *PacketMetadata) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *PacketMetadata) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *PacketMetadata) GetSourceClientId() int64 {
	if x != nil {
		return x.SourceClientId
	}
	return 0
}

func (x *PacketMetadata) GetTargetClientId() int64 {
	if x != nil {
		return x.TargetClientId
	}
	return 0
}

func (x *PacketMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// BridgePacket 桥接数据包（支持多路复用）
type BridgePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"` // 逻辑流ID（用于多路复用）
	Type          PacketType             `protobuf:"varint,2,opt,name=type,proto3,enum=bridge.PacketType" json:"type,omitempty"` // 数据包类型
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                   // 实际数据
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 时间戳（毫秒）
	Metadata      *PacketMetadata        `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`                 // 元数据（强类型）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgePacket) Reset() {
	*x = BridgePacket{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgePacket) ProtoMessage() {}

func (x *BridgePacket) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgePacket.ProtoReflect.Descriptor instead.
func (*BridgePacket) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *BridgePacket) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *BridgePacket) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_UNKNOWN
}

func (x *BridgePacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BridgePacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BridgePacket) GetMetadata() *PacketMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// StreamOpenRequest 打开流请求（放在 BridgePacket.payload 中）
type StreamOpenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceClientId string                 `protobuf:"bytes,1,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"` // 源客户端ID
	TargetClientId string                 `protobuf:"bytes,2,opt,name=target_client_id,json=targetClientId,proto3" json:"target_client_id,omitempty"` // 目标客户端ID
	TargetHost     string                 `protobuf:"bytes,3,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`               // 目标主机
	TargetPort     int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`              // 目标端口
	Protocol       string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`                                     // 协议类型 (tcp/http)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamOpenRequest) Reset() {
	*x = StreamOpenRequest{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOpenRequest) ProtoMessage() {}

func (x *StreamOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOpenRequest.ProtoReflect.Descriptor instead.
func (*StreamOpenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *StreamOpenRequest) GetSourceClientId() string {
	if x != nil {
		return x.SourceClientId
	}
	return ""
}

func (x *StreamOpenRequest) GetTargetClientId() string {
	if x != nil {
		return x.TargetClientId
	}
	return ""
}

func (x *StreamOpenRequest) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *StreamOpenRequest) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *StreamOpenRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// StreamOpenResponse 打开流响应
type StreamOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOpenResponse) Reset() {
	*x = StreamOpenResponse{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOpenResponse) ProtoMessage() {}

func (x *StreamOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOpenResponse.ProtoReflect.Descriptor instead.
func (*StreamOpenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *StreamOpenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamOpenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// StreamCloseRequest 关闭流请求
type StreamCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCloseRequest) Reset() {
	*x = StreamCloseRequest{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCloseRequest) ProtoMessage() {}

func (x *StreamCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCloseRequest.ProtoReflect.Descriptor instead.
func (*StreamCloseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *StreamCloseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// StreamErrorMessage 错误消息
type StreamErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamErrorMessage) Reset() {
	*x = StreamErrorMessage{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamErrorMessage) ProtoMessage() {}

func (x *StreamErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamErrorMessage.ProtoReflect.Descriptor instead.
func (*StreamErrorMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *StreamErrorMessage) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *StreamErrorMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// PingRequest 心跳请求
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *PingRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// PingResponse 心跳响应
type PingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// NodeInfoRequest 节点信息请求
type NodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoRequest) Reset() {
	*x = NodeInfoRequest{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoRequest) ProtoMessage() {}

func (x *NodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoRequest.ProtoReflect.Descriptor instead.
func (*NodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *NodeInfoRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// NodeMetadata 节点元数据（强类型定义）
type NodeMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                   // 版本号
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // 节点类型
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`                     // 区域
	Cluster       string                 `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`                   // 集群名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetadata) Reset() {
	*x = NodeMetadata{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadata) ProtoMessage() {}

func (x *NodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadata.ProtoReflect.Descriptor instead.
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *NodeMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeMetadata) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeMetadata) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NodeMetadata) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

// NodeInfoResponse 节点信息响应
type NodeInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAddress       string                 `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	ActiveStreams     int32                  `protobuf:"varint,4,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Metadata          *NodeMetadata          `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeInfoResponse) Reset() {
	*x = NodeInfoResponse{}
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoResponse) ProtoMessage() {}

func (x *NodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bridge_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoResponse.ProtoReflect.Descriptor instead.
func (*NodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bridge_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *NodeInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfoResponse) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *NodeInfoResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *NodeInfoResponse) GetActiveStreams() int32 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *NodeInfoResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *NodeInfoResponse) GetMetadata() *NodeMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_proto_bridge_bridge_proto protoreflect.FileDescriptor

const file_api_proto_bridge_bridge_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/bridge/bridge.proto\x12\x06bridge\"\xcf\x01\n" +
	"\x0ePacketMetadata\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\x12(\n" +
	"\x10source_client_id\x18\x03 \x01(\x03R\x0esourceClientId\x12(\n" +
	"\x10target_client_id\x18\x04 \x01(\x03R\x0etargetClientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\xbf\x01\n" +
	"\fBridgePacket\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.bridge.PacketTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x122\n" +
	"\bmetadata\x18\x05 \x01(\v2\x16.bridge.PacketMetadataR\bmetadata\"\xc5\x01\n" +
	"\x11StreamOpenRequest\x12(\n" +
	"\x10source_client_id\x18\x01 \x01(\tR\x0esourceClientId\x12(\n" +
	"\x10target_client_id\x18\x02 \x01(\tR\x0etargetClientId\x12\x1f\n" +
	"\vtarget_host\x18\x03 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\"S\n" +
	"\x12StreamOpenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\",\n" +
	"\x12StreamCloseRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"X\n" +
	"\x12StreamErrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"D\n" +
	"\vPingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"I\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\"*\n" +
	"\x0fNodeInfoRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"w\n" +
	"\fNodeMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x18\n" +
	"\acluster\x18\x04 \x01(\tR\acluster\"\xfd\x01\n" +
	"\x10NodeInfoResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fnode_address\x18\x02 \x01(\tR\vnodeAddress\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\x12%\n" +
	"\x0eactive_streams\x18\x04 \x01(\x05R\ractiveStreams\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x120\n" +
	"\bmetadata\x18\x06 \x01(\v2\x14.bridge.NodeMetadataR\bmetadata*o\n" +
	"\n" +
	"PacketType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vSTREAM_OPEN\x10\x01\x12\x0f\n" +
	"\vSTREAM_DATA\x10\x02\x12\x10\n" +
	"\fSTREAM_CLOSE\x10\x03\x12\x0e\n" +
	"\n" +
	"STREAM_ACK\x10\x04\x12\x10\n" +
	"\fSTREAM_ERROR\x10\x052\xc5\x01\n" +
	"\rBridgeService\x12?\n" +
	"\rForwardStream\x12\x14.bridge.BridgePacket\x1a\x14.bridge.BridgePacket(\x010\x01\x121\n" +
	"\x04Ping\x12\x13.bridge.PingRequest\x1a\x14.bridge.PingResponse\x12@\n" +
	"\vGetNodeInfo\x12\x17.bridge.NodeInfoRequest\x1a\x18.bridge.NodeInfoResponseB%Z#tunnox-core/api/proto/bridge;bridgeb\x06proto3"

var (
	file_api_proto_bridge_bridge_proto_rawDescOnce sync.Once
	file_api_proto_bridge_bridge_proto_rawDescData []byte
)

func file_api_proto_bridge_bridge_proto_rawDescGZIP() []byte {
	file_api_proto_bridge_bridge_proto_rawDescOnce.Do(func() {
		file_api_proto_bridge_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_bridge_bridge_proto_rawDesc), len(file_api_proto_bridge_bridge_proto_rawDesc)))
	})
	return file_api_proto_bridge_bridge_proto_rawDescData
}

var file_api_proto_bridge_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_bridge_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_bridge_bridge_proto_goTypes = []any{
	(PacketType)(0),            // 0: bridge.PacketType
	(*PacketMetadata)(nil),     // 1: bridge.PacketMetadata
	(*BridgePacket)(nil),       // 2: bridge.BridgePacket
	(*StreamOpenRequest)(nil),  // 3: bridge.StreamOpenRequest
	(*StreamOpenResponse)(nil), // 4: bridge.StreamOpenResponse
	(*StreamCloseRequest)(nil), // 5: bridge.StreamCloseRequest
	(*StreamErrorMessage)(nil), // 6: bridge.StreamErrorMessage
	(*PingRequest)(nil),        // 7: bridge.PingRequest
	(*PingResponse)(nil),       // 8: bridge.PingResponse
	(*NodeInfoRequest)(nil),    // 9: bridge.NodeInfoRequest
	(*NodeMetadata)(nil),       // 10: bridge.NodeMetadata
	(*NodeInfoResponse)(nil),   // 11: bridge.NodeInfoResponse
}
var file_api_proto_bridge_bridge_proto_depIdxs = []int32{
	0,  // 0: bridge.BridgePacket.type:type_name -> bridge.PacketType
	1,  // 1: bridge.BridgePacket.metadata:type_name -> bridge.PacketMetadata
	10, // 2: bridge.NodeInfoResponse.metadata:type_name -> bridge.NodeMetadata
	2,  // 3: bridge.BridgeService.ForwardStream:input_type -> bridge.BridgePacket
	7,  // 4: bridge.BridgeService.Ping:input_type -> bridge.PingRequest
	9,  // 5: bridge.BridgeService.GetNodeInfo:input_type -> bridge.NodeInfoRequest
	2,  // 6: bridge.BridgeService.ForwardStream:output_type -> bridge.BridgePacket
	8,  // 7: bridge.BridgeService.Ping:output_type -> bridge.PingResponse
	11, // 8: bridge.BridgeService.GetNodeInfo:output_type -> bridge.NodeInfoResponse
	6,  // [6:9] is the sub-list for method output_type
	3,  // [3:6] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_bridge_bridge_proto_init() }
func file_api_proto_bridge_bridge_proto_init() {
	if File_api_proto_bridge_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_bridge_bridge_proto_rawDesc), len(file_api_proto_bridge_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_bridge_bridge_proto_goTypes,
		DependencyIndexes: file_api_proto_bridge_bridge_proto_depIdxs,
		EnumInfos:         file_api_proto_bridge_bridge_proto_enumTypes,
		MessageInfos:      file_api_proto_bridge_bridge_proto_msgTypes,
	}.Build()
	File_api_proto_bridge_bridge_proto = out.File
	file_api_proto_bridge_bridge_proto_goTypes = nil
	file_api_proto_bridge_bridge_proto_depIdxs = nil
}
