// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/proto/storage/storage.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_Set_FullMethodName            = "/storage.StorageService/Set"
	StorageService_Get_FullMethodName            = "/storage.StorageService/Get"
	StorageService_Delete_FullMethodName         = "/storage.StorageService/Delete"
	StorageService_Exists_FullMethodName         = "/storage.StorageService/Exists"
	StorageService_BatchSet_FullMethodName       = "/storage.StorageService/BatchSet"
	StorageService_BatchGet_FullMethodName       = "/storage.StorageService/BatchGet"
	StorageService_BatchDelete_FullMethodName    = "/storage.StorageService/BatchDelete"
	StorageService_SetList_FullMethodName        = "/storage.StorageService/SetList"
	StorageService_GetList_FullMethodName        = "/storage.StorageService/GetList"
	StorageService_AppendToList_FullMethodName   = "/storage.StorageService/AppendToList"
	StorageService_RemoveFromList_FullMethodName = "/storage.StorageService/RemoveFromList"
	StorageService_SetExpiration_FullMethodName  = "/storage.StorageService/SetExpiration"
	StorageService_GetExpiration_FullMethodName  = "/storage.StorageService/GetExpiration"
	StorageService_QueryByField_FullMethodName   = "/storage.StorageService/QueryByField"
	StorageService_QueryByPrefix_FullMethodName  = "/storage.StorageService/QueryByPrefix"
	StorageService_SetNX_FullMethodName          = "/storage.StorageService/SetNX"
	StorageService_Incr_FullMethodName           = "/storage.StorageService/Incr"
	StorageService_Ping_FullMethodName           = "/storage.StorageService/Ping"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageService 存储服务接口
// 供 tunnox-core 的 RemoteStorage 客户端调用
type StorageServiceClient interface {
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 基础 KV 操作
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 批量操作
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	BatchSet(ctx context.Context, in *BatchSetRequest, opts ...grpc.CallOption) (*BatchSetResponse, error)
	BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error)
	BatchDelete(ctx context.Context, in *BatchDeleteRequest, opts ...grpc.CallOption) (*BatchDeleteResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 列表操作
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	SetList(ctx context.Context, in *SetListRequest, opts ...grpc.CallOption) (*SetListResponse, error)
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
	AppendToList(ctx context.Context, in *AppendToListRequest, opts ...grpc.CallOption) (*AppendToListResponse, error)
	RemoveFromList(ctx context.Context, in *RemoveFromListRequest, opts ...grpc.CallOption) (*RemoveFromListResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 过期时间
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	SetExpiration(ctx context.Context, in *SetExpirationRequest, opts ...grpc.CallOption) (*SetExpirationResponse, error)
	GetExpiration(ctx context.Context, in *GetExpirationRequest, opts ...grpc.CallOption) (*GetExpirationResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 查询操作
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	QueryByField(ctx context.Context, in *QueryByFieldRequest, opts ...grpc.CallOption) (*QueryByFieldResponse, error)
	QueryByPrefix(ctx context.Context, in *QueryByPrefixRequest, opts ...grpc.CallOption) (*QueryByPrefixResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 原子操作
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	SetNX(ctx context.Context, in *SetNXRequest, opts ...grpc.CallOption) (*SetNXResponse, error)
	Incr(ctx context.Context, in *IncrRequest, opts ...grpc.CallOption) (*IncrResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 健康检查
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, StorageService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, StorageService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, StorageService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, StorageService_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) BatchSet(ctx context.Context, in *BatchSetRequest, opts ...grpc.CallOption) (*BatchSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSetResponse)
	err := c.cc.Invoke(ctx, StorageService_BatchSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetResponse)
	err := c.cc.Invoke(ctx, StorageService_BatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) BatchDelete(ctx context.Context, in *BatchDeleteRequest, opts ...grpc.CallOption) (*BatchDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDeleteResponse)
	err := c.cc.Invoke(ctx, StorageService_BatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SetList(ctx context.Context, in *SetListRequest, opts ...grpc.CallOption) (*SetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetListResponse)
	err := c.cc.Invoke(ctx, StorageService_SetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, StorageService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) AppendToList(ctx context.Context, in *AppendToListRequest, opts ...grpc.CallOption) (*AppendToListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendToListResponse)
	err := c.cc.Invoke(ctx, StorageService_AppendToList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) RemoveFromList(ctx context.Context, in *RemoveFromListRequest, opts ...grpc.CallOption) (*RemoveFromListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromListResponse)
	err := c.cc.Invoke(ctx, StorageService_RemoveFromList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SetExpiration(ctx context.Context, in *SetExpirationRequest, opts ...grpc.CallOption) (*SetExpirationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetExpirationResponse)
	err := c.cc.Invoke(ctx, StorageService_SetExpiration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetExpiration(ctx context.Context, in *GetExpirationRequest, opts ...grpc.CallOption) (*GetExpirationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpirationResponse)
	err := c.cc.Invoke(ctx, StorageService_GetExpiration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) QueryByField(ctx context.Context, in *QueryByFieldRequest, opts ...grpc.CallOption) (*QueryByFieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryByFieldResponse)
	err := c.cc.Invoke(ctx, StorageService_QueryByField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) QueryByPrefix(ctx context.Context, in *QueryByPrefixRequest, opts ...grpc.CallOption) (*QueryByPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryByPrefixResponse)
	err := c.cc.Invoke(ctx, StorageService_QueryByPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SetNX(ctx context.Context, in *SetNXRequest, opts ...grpc.CallOption) (*SetNXResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNXResponse)
	err := c.cc.Invoke(ctx, StorageService_SetNX_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Incr(ctx context.Context, in *IncrRequest, opts ...grpc.CallOption) (*IncrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrResponse)
	err := c.cc.Invoke(ctx, StorageService_Incr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, StorageService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// StorageService 存储服务接口
// 供 tunnox-core 的 RemoteStorage 客户端调用
type StorageServiceServer interface {
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 基础 KV 操作
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Exists(context.Context, *ExistsRequest) (*ExistsResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 批量操作
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	BatchSet(context.Context, *BatchSetRequest) (*BatchSetResponse, error)
	BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error)
	BatchDelete(context.Context, *BatchDeleteRequest) (*BatchDeleteResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 列表操作
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	SetList(context.Context, *SetListRequest) (*SetListResponse, error)
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	AppendToList(context.Context, *AppendToListRequest) (*AppendToListResponse, error)
	RemoveFromList(context.Context, *RemoveFromListRequest) (*RemoveFromListResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 过期时间
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	SetExpiration(context.Context, *SetExpirationRequest) (*SetExpirationResponse, error)
	GetExpiration(context.Context, *GetExpirationRequest) (*GetExpirationResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 查询操作
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	QueryByField(context.Context, *QueryByFieldRequest) (*QueryByFieldResponse, error)
	QueryByPrefix(context.Context, *QueryByPrefixRequest) (*QueryByPrefixResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 原子操作
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	SetNX(context.Context, *SetNXRequest) (*SetNXResponse, error)
	Incr(context.Context, *IncrRequest) (*IncrResponse, error)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// 健康检查
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedStorageServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStorageServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStorageServiceServer) Exists(context.Context, *ExistsRequest) (*ExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedStorageServiceServer) BatchSet(context.Context, *BatchSetRequest) (*BatchSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchSet not implemented")
}
func (UnimplementedStorageServiceServer) BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGet not implemented")
}
func (UnimplementedStorageServiceServer) BatchDelete(context.Context, *BatchDeleteRequest) (*BatchDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDelete not implemented")
}
func (UnimplementedStorageServiceServer) SetList(context.Context, *SetListRequest) (*SetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetList not implemented")
}
func (UnimplementedStorageServiceServer) GetList(context.Context, *GetListRequest) (*GetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedStorageServiceServer) AppendToList(context.Context, *AppendToListRequest) (*AppendToListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendToList not implemented")
}
func (UnimplementedStorageServiceServer) RemoveFromList(context.Context, *RemoveFromListRequest) (*RemoveFromListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromList not implemented")
}
func (UnimplementedStorageServiceServer) SetExpiration(context.Context, *SetExpirationRequest) (*SetExpirationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetExpiration not implemented")
}
func (UnimplementedStorageServiceServer) GetExpiration(context.Context, *GetExpirationRequest) (*GetExpirationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpiration not implemented")
}
func (UnimplementedStorageServiceServer) QueryByField(context.Context, *QueryByFieldRequest) (*QueryByFieldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryByField not implemented")
}
func (UnimplementedStorageServiceServer) QueryByPrefix(context.Context, *QueryByPrefixRequest) (*QueryByPrefixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryByPrefix not implemented")
}
func (UnimplementedStorageServiceServer) SetNX(context.Context, *SetNXRequest) (*SetNXResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNX not implemented")
}
func (UnimplementedStorageServiceServer) Incr(context.Context, *IncrRequest) (*IncrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Incr not implemented")
}
func (UnimplementedStorageServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_BatchSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).BatchSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_BatchSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).BatchSet(ctx, req.(*BatchSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_BatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).BatchGet(ctx, req.(*BatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_BatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).BatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_BatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).BatchDelete(ctx, req.(*BatchDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_SetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SetList(ctx, req.(*SetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_AppendToList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendToListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).AppendToList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_AppendToList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).AppendToList(ctx, req.(*AppendToListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_RemoveFromList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).RemoveFromList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_RemoveFromList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).RemoveFromList(ctx, req.(*RemoveFromListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SetExpiration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetExpirationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SetExpiration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_SetExpiration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SetExpiration(ctx, req.(*SetExpirationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetExpiration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpirationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetExpiration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetExpiration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetExpiration(ctx, req.(*GetExpirationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_QueryByField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).QueryByField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_QueryByField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).QueryByField(ctx, req.(*QueryByFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_QueryByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).QueryByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_QueryByPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).QueryByPrefix(ctx, req.(*QueryByPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SetNX_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNXRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SetNX(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_SetNX_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SetNX(ctx, req.(*SetNXRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Incr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Incr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Incr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Incr(ctx, req.(*IncrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _StorageService_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StorageService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StorageService_Delete_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _StorageService_Exists_Handler,
		},
		{
			MethodName: "BatchSet",
			Handler:    _StorageService_BatchSet_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _StorageService_BatchGet_Handler,
		},
		{
			MethodName: "BatchDelete",
			Handler:    _StorageService_BatchDelete_Handler,
		},
		{
			MethodName: "SetList",
			Handler:    _StorageService_SetList_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _StorageService_GetList_Handler,
		},
		{
			MethodName: "AppendToList",
			Handler:    _StorageService_AppendToList_Handler,
		},
		{
			MethodName: "RemoveFromList",
			Handler:    _StorageService_RemoveFromList_Handler,
		},
		{
			MethodName: "SetExpiration",
			Handler:    _StorageService_SetExpiration_Handler,
		},
		{
			MethodName: "GetExpiration",
			Handler:    _StorageService_GetExpiration_Handler,
		},
		{
			MethodName: "QueryByField",
			Handler:    _StorageService_QueryByField_Handler,
		},
		{
			MethodName: "QueryByPrefix",
			Handler:    _StorageService_QueryByPrefix_Handler,
		},
		{
			MethodName: "SetNX",
			Handler:    _StorageService_SetNX_Handler,
		},
		{
			MethodName: "Incr",
			Handler:    _StorageService_Incr_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _StorageService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/storage/storage.proto",
}
