// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/storage/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                              // JSON 序列化的值
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 过期时间（秒），0 表示永不过期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsRequest) Reset() {
	*x = ExistsRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsRequest) ProtoMessage() {}

func (x *ExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsRequest.ProtoReflect.Descriptor instead.
func (*ExistsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{6}
}

func (x *ExistsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{7}
}

func (x *ExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ExistsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{8}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type BatchSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KeyValue            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetRequest) Reset() {
	*x = BatchSetRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetRequest) ProtoMessage() {}

func (x *BatchSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetRequest.ProtoReflect.Descriptor instead.
func (*BatchSetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{9}
}

func (x *BatchSetRequest) GetItems() []*KeyValue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchSetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type BatchSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetResponse) Reset() {
	*x = BatchSetResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetResponse) ProtoMessage() {}

func (x *BatchSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetResponse.ProtoReflect.Descriptor instead.
func (*BatchSetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{10}
}

func (x *BatchSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchSetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{11}
}

func (x *BatchGetRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KeyValue            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetResponse) GetItems() []*KeyValue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteRequest) Reset() {
	*x = BatchDeleteRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteRequest) ProtoMessage() {}

func (x *BatchDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{13}
}

func (x *BatchDeleteRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BatchDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeletedCount  int64                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteResponse) Reset() {
	*x = BatchDeleteResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteResponse) ProtoMessage() {}

func (x *BatchDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteResponse.ProtoReflect.Descriptor instead.
func (*BatchDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{14}
}

func (x *BatchDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchDeleteResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *BatchDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        [][]byte               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetListRequest) Reset() {
	*x = SetListRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListRequest) ProtoMessage() {}

func (x *SetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListRequest.ProtoReflect.Descriptor instead.
func (*SetListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{15}
}

func (x *SetListRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetListRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SetListRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetListResponse) Reset() {
	*x = SetListResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListResponse) ProtoMessage() {}

func (x *SetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListResponse.ProtoReflect.Descriptor instead.
func (*SetListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{16}
}

func (x *SetListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRequest) Reset() {
	*x = GetListRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRequest) ProtoMessage() {}

func (x *GetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRequest.ProtoReflect.Descriptor instead.
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{17}
}

func (x *GetListRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListResponse) Reset() {
	*x = GetListResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListResponse) ProtoMessage() {}

func (x *GetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListResponse.ProtoReflect.Descriptor instead.
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{18}
}

func (x *GetListResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GetListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AppendToListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendToListRequest) Reset() {
	*x = AppendToListRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendToListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendToListRequest) ProtoMessage() {}

func (x *AppendToListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendToListRequest.ProtoReflect.Descriptor instead.
func (*AppendToListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{19}
}

func (x *AppendToListRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AppendToListRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type AppendToListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendToListResponse) Reset() {
	*x = AppendToListResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendToListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendToListResponse) ProtoMessage() {}

func (x *AppendToListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendToListResponse.ProtoReflect.Descriptor instead.
func (*AppendToListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{20}
}

func (x *AppendToListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendToListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemoveFromListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromListRequest) Reset() {
	*x = RemoveFromListRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromListRequest) ProtoMessage() {}

func (x *RemoveFromListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromListRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveFromListRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RemoveFromListRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RemoveFromListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromListResponse) Reset() {
	*x = RemoveFromListResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromListResponse) ProtoMessage() {}

func (x *RemoveFromListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromListResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveFromListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveFromListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetExpirationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetExpirationRequest) Reset() {
	*x = SetExpirationRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExpirationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExpirationRequest) ProtoMessage() {}

func (x *SetExpirationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExpirationRequest.ProtoReflect.Descriptor instead.
func (*SetExpirationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{23}
}

func (x *SetExpirationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetExpirationRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetExpirationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetExpirationResponse) Reset() {
	*x = SetExpirationResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExpirationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExpirationResponse) ProtoMessage() {}

func (x *SetExpirationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExpirationResponse.ProtoReflect.Descriptor instead.
func (*SetExpirationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{24}
}

func (x *SetExpirationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetExpirationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetExpirationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpirationRequest) Reset() {
	*x = GetExpirationRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpirationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpirationRequest) ProtoMessage() {}

func (x *GetExpirationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpirationRequest.ProtoReflect.Descriptor instead.
func (*GetExpirationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{25}
}

func (x *GetExpirationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetExpirationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtlSeconds    int64                  `protobuf:"varint,1,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // -1 表示永不过期，-2 表示 key 不存在
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpirationResponse) Reset() {
	*x = GetExpirationResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpirationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpirationResponse) ProtoMessage() {}

func (x *GetExpirationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpirationResponse.ProtoReflect.Descriptor instead.
func (*GetExpirationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{26}
}

func (x *GetExpirationResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *GetExpirationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueryByFieldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPrefix     string                 `protobuf:"bytes,1,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	FieldName     string                 `protobuf:"bytes,2,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldValue    []byte                 `protobuf:"bytes,3,opt,name=field_value,json=fieldValue,proto3" json:"field_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryByFieldRequest) Reset() {
	*x = QueryByFieldRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryByFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryByFieldRequest) ProtoMessage() {}

func (x *QueryByFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryByFieldRequest.ProtoReflect.Descriptor instead.
func (*QueryByFieldRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{27}
}

func (x *QueryByFieldRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *QueryByFieldRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *QueryByFieldRequest) GetFieldValue() []byte {
	if x != nil {
		return x.FieldValue
	}
	return nil
}

type QueryByFieldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryByFieldResponse) Reset() {
	*x = QueryByFieldResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryByFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryByFieldResponse) ProtoMessage() {}

func (x *QueryByFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryByFieldResponse.ProtoReflect.Descriptor instead.
func (*QueryByFieldResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{28}
}

func (x *QueryByFieldResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *QueryByFieldResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueryByPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 0 表示无限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryByPrefixRequest) Reset() {
	*x = QueryByPrefixRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryByPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryByPrefixRequest) ProtoMessage() {}

func (x *QueryByPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryByPrefixRequest.ProtoReflect.Descriptor instead.
func (*QueryByPrefixRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{29}
}

func (x *QueryByPrefixRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *QueryByPrefixRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryByPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KeyValue            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryByPrefixResponse) Reset() {
	*x = QueryByPrefixResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryByPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryByPrefixResponse) ProtoMessage() {}

func (x *QueryByPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryByPrefixResponse.ProtoReflect.Descriptor instead.
func (*QueryByPrefixResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{30}
}

func (x *QueryByPrefixResponse) GetItems() []*KeyValue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *QueryByPrefixResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetNXRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNXRequest) Reset() {
	*x = SetNXRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNXRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNXRequest) ProtoMessage() {}

func (x *SetNXRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNXRequest.ProtoReflect.Descriptor instead.
func (*SetNXRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{31}
}

func (x *SetNXRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetNXRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetNXRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetNXResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // true 表示设置成功，false 表示 key 已存在
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNXResponse) Reset() {
	*x = SetNXResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNXResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNXResponse) ProtoMessage() {}

func (x *SetNXResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNXResponse.ProtoReflect.Descriptor instead.
func (*SetNXResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{32}
}

func (x *SetNXResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetNXResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IncrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"` // 增量值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrRequest) Reset() {
	*x = IncrRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrRequest) ProtoMessage() {}

func (x *IncrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrRequest.ProtoReflect.Descriptor instead.
func (*IncrRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{33}
}

func (x *IncrRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IncrRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type IncrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"` // 增加后的值
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrResponse) Reset() {
	*x = IncrResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrResponse) ProtoMessage() {}

func (x *IncrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrResponse.ProtoReflect.Descriptor instead.
func (*IncrResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{34}
}

func (x *IncrResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IncrResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{35}
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ClientAddress   string                 `protobuf:"bytes,4,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"` // 客户端的真实 IP 地址（用于节点发现）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_storage_storage_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_storage_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_storage_proto_rawDescGZIP(), []int{36}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

var File_api_proto_storage_storage_proto protoreflect.FileDescriptor

const file_api_proto_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/storage/storage.proto\x12\astorage\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"=\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"O\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"@\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"!\n" +
	"\rExistsRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\">\n" +
	"\x0eExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"[\n" +
	"\x0fBatchSetRequest\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.storage.KeyValueR\x05items\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"B\n" +
	"\x10BatchSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"%\n" +
	"\x0fBatchGetRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"Q\n" +
	"\x10BatchGetResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.storage.KeyValueR\x05items\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x12BatchDeleteRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"j\n" +
	"\x13BatchDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x03R\fdeletedCount\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"[\n" +
	"\x0eSetListRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\fR\x06values\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"A\n" +
	"\x0fSetListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\"\n" +
	"\x0eGetListRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"?\n" +
	"\x0fGetListResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"=\n" +
	"\x13AppendToListRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"F\n" +
	"\x14AppendToListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"?\n" +
	"\x15RemoveFromListRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"H\n" +
	"\x16RemoveFromListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"I\n" +
	"\x14SetExpirationRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"G\n" +
	"\x15SetExpirationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x14GetExpirationRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"N\n" +
	"\x15GetExpirationResponse\x12\x1f\n" +
	"\vttl_seconds\x18\x01 \x01(\x03R\n" +
	"ttlSeconds\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"t\n" +
	"\x13QueryByFieldRequest\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x01 \x01(\tR\tkeyPrefix\x12\x1d\n" +
	"\n" +
	"field_name\x18\x02 \x01(\tR\tfieldName\x12\x1f\n" +
	"\vfield_value\x18\x03 \x01(\fR\n" +
	"fieldValue\"@\n" +
	"\x14QueryByFieldResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"D\n" +
	"\x14QueryByPrefixRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"V\n" +
	"\x15QueryByPrefixResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.storage.KeyValueR\x05items\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"W\n" +
	"\fSetNXRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"?\n" +
	"\rSetNXResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\vIncrRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\":\n" +
	"\fIncrResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\vPingRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x8a\x01\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0eclient_address\x18\x04 \x01(\tR\rclientAddress2\xb1\t\n" +
	"\x0eStorageService\x120\n" +
	"\x03Set\x12\x13.storage.SetRequest\x1a\x14.storage.SetResponse\x120\n" +
	"\x03Get\x12\x13.storage.GetRequest\x1a\x14.storage.GetResponse\x129\n" +
	"\x06Delete\x12\x16.storage.DeleteRequest\x1a\x17.storage.DeleteResponse\x129\n" +
	"\x06Exists\x12\x16.storage.ExistsRequest\x1a\x17.storage.ExistsResponse\x12?\n" +
	"\bBatchSet\x12\x18.storage.BatchSetRequest\x1a\x19.storage.BatchSetResponse\x12?\n" +
	"\bBatchGet\x12\x18.storage.BatchGetRequest\x1a\x19.storage.BatchGetResponse\x12H\n" +
	"\vBatchDelete\x12\x1b.storage.BatchDeleteRequest\x1a\x1c.storage.BatchDeleteResponse\x12<\n" +
	"\aSetList\x12\x17.storage.SetListRequest\x1a\x18.storage.SetListResponse\x12<\n" +
	"\aGetList\x12\x17.storage.GetListRequest\x1a\x18.storage.GetListResponse\x12K\n" +
	"\fAppendToList\x12\x1c.storage.AppendToListRequest\x1a\x1d.storage.AppendToListResponse\x12Q\n" +
	"\x0eRemoveFromList\x12\x1e.storage.RemoveFromListRequest\x1a\x1f.storage.RemoveFromListResponse\x12N\n" +
	"\rSetExpiration\x12\x1d.storage.SetExpirationRequest\x1a\x1e.storage.SetExpirationResponse\x12N\n" +
	"\rGetExpiration\x12\x1d.storage.GetExpirationRequest\x1a\x1e.storage.GetExpirationResponse\x12K\n" +
	"\fQueryByField\x12\x1c.storage.QueryByFieldRequest\x1a\x1d.storage.QueryByFieldResponse\x12N\n" +
	"\rQueryByPrefix\x12\x1d.storage.QueryByPrefixRequest\x1a\x1e.storage.QueryByPrefixResponse\x126\n" +
	"\x05SetNX\x12\x15.storage.SetNXRequest\x1a\x16.storage.SetNXResponse\x123\n" +
	"\x04Incr\x12\x14.storage.IncrRequest\x1a\x15.storage.IncrResponse\x123\n" +
	"\x04Ping\x12\x14.storage.PingRequest\x1a\x15.storage.PingResponseB'Z%tunnox-core/api/proto/storage;storageb\x06proto3"

var (
	file_api_proto_storage_storage_proto_rawDescOnce sync.Once
	file_api_proto_storage_storage_proto_rawDescData []byte
)

func file_api_proto_storage_storage_proto_rawDescGZIP() []byte {
	file_api_proto_storage_storage_proto_rawDescOnce.Do(func() {
		file_api_proto_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_storage_storage_proto_rawDesc), len(file_api_proto_storage_storage_proto_rawDesc)))
	})
	return file_api_proto_storage_storage_proto_rawDescData
}

var file_api_proto_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_api_proto_storage_storage_proto_goTypes = []any{
	(*SetRequest)(nil),             // 0: storage.SetRequest
	(*SetResponse)(nil),            // 1: storage.SetResponse
	(*GetRequest)(nil),             // 2: storage.GetRequest
	(*GetResponse)(nil),            // 3: storage.GetResponse
	(*DeleteRequest)(nil),          // 4: storage.DeleteRequest
	(*DeleteResponse)(nil),         // 5: storage.DeleteResponse
	(*ExistsRequest)(nil),          // 6: storage.ExistsRequest
	(*ExistsResponse)(nil),         // 7: storage.ExistsResponse
	(*KeyValue)(nil),               // 8: storage.KeyValue
	(*BatchSetRequest)(nil),        // 9: storage.BatchSetRequest
	(*BatchSetResponse)(nil),       // 10: storage.BatchSetResponse
	(*BatchGetRequest)(nil),        // 11: storage.BatchGetRequest
	(*BatchGetResponse)(nil),       // 12: storage.BatchGetResponse
	(*BatchDeleteRequest)(nil),     // 13: storage.BatchDeleteRequest
	(*BatchDeleteResponse)(nil),    // 14: storage.BatchDeleteResponse
	(*SetListRequest)(nil),         // 15: storage.SetListRequest
	(*SetListResponse)(nil),        // 16: storage.SetListResponse
	(*GetListRequest)(nil),         // 17: storage.GetListRequest
	(*GetListResponse)(nil),        // 18: storage.GetListResponse
	(*AppendToListRequest)(nil),    // 19: storage.AppendToListRequest
	(*AppendToListResponse)(nil),   // 20: storage.AppendToListResponse
	(*RemoveFromListRequest)(nil),  // 21: storage.RemoveFromListRequest
	(*RemoveFromListResponse)(nil), // 22: storage.RemoveFromListResponse
	(*SetExpirationRequest)(nil),   // 23: storage.SetExpirationRequest
	(*SetExpirationResponse)(nil),  // 24: storage.SetExpirationResponse
	(*GetExpirationRequest)(nil),   // 25: storage.GetExpirationRequest
	(*GetExpirationResponse)(nil),  // 26: storage.GetExpirationResponse
	(*QueryByFieldRequest)(nil),    // 27: storage.QueryByFieldRequest
	(*QueryByFieldResponse)(nil),   // 28: storage.QueryByFieldResponse
	(*QueryByPrefixRequest)(nil),   // 29: storage.QueryByPrefixRequest
	(*QueryByPrefixResponse)(nil),  // 30: storage.QueryByPrefixResponse
	(*SetNXRequest)(nil),           // 31: storage.SetNXRequest
	(*SetNXResponse)(nil),          // 32: storage.SetNXResponse
	(*IncrRequest)(nil),            // 33: storage.IncrRequest
	(*IncrResponse)(nil),           // 34: storage.IncrResponse
	(*PingRequest)(nil),            // 35: storage.PingRequest
	(*PingResponse)(nil),           // 36: storage.PingResponse
}
var file_api_proto_storage_storage_proto_depIdxs = []int32{
	8,  // 0: storage.BatchSetRequest.items:type_name -> storage.KeyValue
	8,  // 1: storage.BatchGetResponse.items:type_name -> storage.KeyValue
	8,  // 2: storage.QueryByPrefixResponse.items:type_name -> storage.KeyValue
	0,  // 3: storage.StorageService.Set:input_type -> storage.SetRequest
	2,  // 4: storage.StorageService.Get:input_type -> storage.GetRequest
	4,  // 5: storage.StorageService.Delete:input_type -> storage.DeleteRequest
	6,  // 6: storage.StorageService.Exists:input_type -> storage.ExistsRequest
	9,  // 7: storage.StorageService.BatchSet:input_type -> storage.BatchSetRequest
	11, // 8: storage.StorageService.BatchGet:input_type -> storage.BatchGetRequest
	13, // 9: storage.StorageService.BatchDelete:input_type -> storage.BatchDeleteRequest
	15, // 10: storage.StorageService.SetList:input_type -> storage.SetListRequest
	17, // 11: storage.StorageService.GetList:input_type -> storage.GetListRequest
	19, // 12: storage.StorageService.AppendToList:input_type -> storage.AppendToListRequest
	21, // 13: storage.StorageService.RemoveFromList:input_type -> storage.RemoveFromListRequest
	23, // 14: storage.StorageService.SetExpiration:input_type -> storage.SetExpirationRequest
	25, // 15: storage.StorageService.GetExpiration:input_type -> storage.GetExpirationRequest
	27, // 16: storage.StorageService.QueryByField:input_type -> storage.QueryByFieldRequest
	29, // 17: storage.StorageService.QueryByPrefix:input_type -> storage.QueryByPrefixRequest
	31, // 18: storage.StorageService.SetNX:input_type -> storage.SetNXRequest
	33, // 19: storage.StorageService.Incr:input_type -> storage.IncrRequest
	35, // 20: storage.StorageService.Ping:input_type -> storage.PingRequest
	1,  // 21: storage.StorageService.Set:output_type -> storage.SetResponse
	3,  // 22: storage.StorageService.Get:output_type -> storage.GetResponse
	5,  // 23: storage.StorageService.Delete:output_type -> storage.DeleteResponse
	7,  // 24: storage.StorageService.Exists:output_type -> storage.ExistsResponse
	10, // 25: storage.StorageService.BatchSet:output_type -> storage.BatchSetResponse
	12, // 26: storage.StorageService.BatchGet:output_type -> storage.BatchGetResponse
	14, // 27: storage.StorageService.BatchDelete:output_type -> storage.BatchDeleteResponse
	16, // 28: storage.StorageService.SetList:output_type -> storage.SetListResponse
	18, // 29: storage.StorageService.GetList:output_type -> storage.GetListResponse
	20, // 30: storage.StorageService.AppendToList:output_type -> storage.AppendToListResponse
	22, // 31: storage.StorageService.RemoveFromList:output_type -> storage.RemoveFromListResponse
	24, // 32: storage.StorageService.SetExpiration:output_type -> storage.SetExpirationResponse
	26, // 33: storage.StorageService.GetExpiration:output_type -> storage.GetExpirationResponse
	28, // 34: storage.StorageService.QueryByField:output_type -> storage.QueryByFieldResponse
	30, // 35: storage.StorageService.QueryByPrefix:output_type -> storage.QueryByPrefixResponse
	32, // 36: storage.StorageService.SetNX:output_type -> storage.SetNXResponse
	34, // 37: storage.StorageService.Incr:output_type -> storage.IncrResponse
	36, // 38: storage.StorageService.Ping:output_type -> storage.PingResponse
	21, // [21:39] is the sub-list for method output_type
	3,  // [3:21] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_storage_storage_proto_init() }
func file_api_proto_storage_storage_proto_init() {
	if File_api_proto_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_storage_storage_proto_rawDesc), len(file_api_proto_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_storage_storage_proto_goTypes,
		DependencyIndexes: file_api_proto_storage_storage_proto_depIdxs,
		MessageInfos:      file_api_proto_storage_storage_proto_msgTypes,
	}.Build()
	File_api_proto_storage_storage_proto = out.File
	file_api_proto_storage_storage_proto_goTypes = nil
	file_api_proto_storage_storage_proto_depIdxs = nil
}
